### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by delatbabel** [vimeo/omnipay-vindicia#5]
Hi Nicky,

Thanks for contributing to Omnipay.  Here are some suggestions after reading the code.

I would put a link to the actual gateway in the README.md file.  I think it's this one, correct? https://www.vindicia.com/  It doesn't hurt to have a language-neutral sentence or two about the gateway and their business operations there.  e.g. something like "Vindicia is a payment service provider headquartered in Redwood City, California, United States. Vindicia sells subscriptions or digital goods such as virtual currency and virtual goods.".  In this case I just quoted from their wikipedia article.

A little more by the way of code examples in some of the class docblocks might help, since this seems to be a fairly complex gateway with lots of options.  e.g. some examples of actually creating a transaction via each of the gateways.  I see you have a good example in the README, maybe add versions of that to each of the gateways.  Have a look at PayPal_REST for some ideas.

Another example -- in the Messages/CaptureRequest class I would add an example of creating an authorization and then capturing it, just so people new to the gateway understand how that's done.

Other than that the code looks good and fairly clean. I see that you have travis set up and tests are passing.

**Comment by nickyr** [comment]
Thanks for the feedback @delatbabel! There are some examples and details about parameters in the Gateway classes themselves, are those good or do they need more detail? Would it be better to put those in the request classes? I'll definitely add some examples of multiple requests in succession like you mentioned with authorize and capture.

**Comment by delatbabel** [comment]
Yes I saw the examples in the gateway classes.  I would add a bit more detail -- continue the process of showing setting up the parameters and go to the point of actually creating a transaction.  If you see in the PayPal_REST gateway I have shown the entire process from creating an Omnipay object to creating a purchase() transaction -- that being the most common transaction.

Another example is here:

https://github.com/thephpleague/omnipay-pin/blob/master/src/Gateway.php

In the gateway class I would just document how to make a purchase() as the most common type of transaction.  You can duplicate that docblock into the PurchaseRequest class.  Then in the other transaction types, if the method to create that transaction is a little "quirky" then include some example of that as well.  e.g. in PayPal_REST there are some unusual methods about fetching transactions based on date ranges which other gateways don't have, so I have included examples of these.

Correct for authorize() and capture() -- because these transactions are also a little quirky I like to include examples.  People understand a purchase() pretty well but someone unfamiliar with gateways and how they work may not know much about authorize() and capture().  Another thing to note in the docblock (and/or the example) is how the transactionReference is used.  For example, in PayPal you have to store the transactionReference from the authorize() if you want to do a refund on that transaction, but in other gateways it's the transactionReference from the capture() that matters.

It's also useful to note when void() and when refund() can be used.  e.g. some gateways do not support void() at all on captured transactions, only on authorize() transactions, so if you have a captured transaction it can only be refunded not voided.  Some other gateways support both.

**Comment by nickyr** [comment]
Okey dokey, I'll work on this tomorrow! Thanks!

**Comment by nickyr** [comment]
Alright @delatbabel, I've made all your suggestions! There's a description of Vindicia in the README and I've embellished the documentation and added a lot more complete examples. Closing this for now, but if you're not satisfied with my changes or you have any other suggestions, let me know and I'll re-open it. Thanks!
